[profile.default]
optimizer_runs = 1000000

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
arbitrum = "${RPC_URL_ARBITRUM}"
avalanche = "${RPC_URL_AVALANCHE}"
base = "${RPC_URL_BASE}"
fantom = "${RPC_URL_FANTOM}"
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"
optimism = "${RPC_URL_OPTIMISM}"
polygon = "${RPC_URL_POLYGON}"
sepolia = "${RPC_URL_SEPOLIA}"

[etherscan]
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
avalanche = {key = "${SNOWTRACE_KEY}", url = "https://api.snowtrace.io/api"}
base = {key = "${BASESCAN_KEY}", url = "https://api.basescan.org/api"}
fantom = {key = "${FTMSCAN_KEY}", url = "https://api.ftmscan.com/api"}
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
optimism = {key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api"}
polygon = {key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api"}
sepolia = {key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api"}
